"""Mandarin Modern Level 1 lesson scripts for rule-based dialogue."""

LESSONS = {
    "lesson_1_greetings": {
        "title": "Lesson 1 — Greetings",
        "description": "Basic greetings and self-introduction.",
        "steps": [
            {
                "id": "greet_1",
                "bot": "你好！欢迎来到 Laoshi Rara。你叫什么名字？",
                "bot_pinyin": "Nǐ hǎo! Huānyíng lái dào YoPengyou. Nǐ jiào shénme míngzi?",
                "bot_english": "Hello! Welcome to Laoshi Rara. What is your name?",
                "bot_malay": "Helo! Selamat datang ke Laoshi Rara. Apa nama awak?",
                "expected_keywords": ["叫", "我是", "名字", "jiao", "wo shi", "mingzi"],
                "hint_en": "Try: wo jiao [your name]",
                "hint_ms": "Cuba: wo jiao [nama awak]",
                "speak_target": None,
            },
            {
                "id": "greet_2",
                "bot": "很高兴认识你！请说：你好 (nǐ hǎo)。",
                "bot_pinyin": "Hěn gāoxìng rènshi nǐ! Qǐng shuō: nǐ hǎo.",
                "bot_english": "Nice to meet you! Please say: hello (nǐ hǎo).",
                "bot_malay": "Gembira berkenalan! Sila sebut: helo (ni hao).",
                "expected_keywords": ["你好", "ni hao", "nihao"],
                "hint_en": "Type ni hao or hello.",
                "hint_ms": "Taip ni hao atau hello.",
                "speak_target": {
                    "word": "你好",
                    "pinyin": "nǐ hǎo",
                    "english": "Hello",
                    "malay": "Helo",
                    "expected_tone": 3,
                    "note": "Both syllables use Tone 3 (low-dip-rise).",
                },
            },
            {
                "id": "greet_3",
                "bot": "很好！现在请说：谢谢 (xièxie)。",
                "bot_pinyin": "Hěn hǎo! Xiànzài qǐng shuō: xièxie.",
                "bot_english": "Very good! Now please say: thank you (xièxie).",
                "bot_malay": "Bagus! Sekarang sila sebut: terima kasih (xièxie).",
                "expected_keywords": ["谢谢", "xiexie", "xie xie"],
                "hint_en": "Type xiexie or thank you.",
                "hint_ms": "Taip xiexie atau thank you.",
                "speak_target": {
                    "word": "谢谢",
                    "pinyin": "xièxie",
                    "english": "Thank you",
                    "malay": "Terima kasih",
                    "expected_tone": 4,
                    "note": "Tone 4 (falling) on both syllables.",
                },
            },
        ],
    },
    "lesson_2_tones": {
        "title": "Lesson 2 — Four Tones",
        "description": "Practice the four Mandarin tones using ma.",
        "steps": [
            {
                "id": "tone_intro",
                "bot": "中文有四个声调。我们先练习「妈、麻、马、骂」。请用文字回复：准备好了",
                "bot_pinyin": "Zhōngwén yǒu sì ge shēngdiào.",
                "bot_english": "Chinese has four tones. We will practice mā, má, mǎ, mà. Reply: ready.",
                "bot_malay": "Bahasa Cina ada empat nada. Kita latih mā, má, mǎ, mà. Balas: sedia.",
                "expected_keywords": ["准备", "好", "ready", "zhunbei", "hao", "sedia"],
                "hint_en": "Type ready or sedia when you are ready.",
                "hint_ms": "Taip ready atau sedia bila sudah bersedia.",
                "speak_target": None,
            },
            {
                "id": "tone_ma1",
                "bot": "请朗读：妈 (mā) — Tone 1, high flat.",
                "bot_pinyin": "Qǐng lǎngdú: mā — dì yī shēng.",
                "bot_english": "Please read: mā — Tone 1, high and flat.",
                "bot_malay": "Sila baca: mā — Nada 1, rata tinggi.",
                "expected_keywords": ["妈", "ma", "tone 1", "第一声"],
                "hint_en": "Say ma (mā) with a high flat tone.",
                "hint_ms": "Sebut ma (mā) dengan nada rata tinggi.",
                "speak_target": {
                    "word": "妈",
                    "pinyin": "mā",
                    "english": "Mother",
                    "malay": "Ibu",
                    "expected_tone": 1,
                    "note": "Tone 1: high and level (mother).",
                },
            },
            {
                "id": "tone_ma2",
                "bot": "请朗读：麻 (má) — Tone 2, rising.",
                "bot_pinyin": "Qǐng lǎngdú: má — dì èr shēng.",
                "bot_english": "Please read: má — Tone 2, rising.",
                "bot_malay": "Sila baca: má — Nada 2, naik.",
                "expected_keywords": ["麻", "ma", "tone 2", "第二声"],
                "hint_en": "Say ma (má) with a rising tone.",
                "hint_ms": "Sebut ma (má) dengan nada naik.",
                "speak_target": {
                    "word": "麻",
                    "pinyin": "má",
                    "english": "Hemp",
                    "malay": "Rami",
                    "expected_tone": 2,
                    "note": "Tone 2: rising (hemp).",
                },
            },
            {
                "id": "tone_ma3",
                "bot": "请朗读：马 (mǎ) — Tone 3, dipping.",
                "bot_pinyin": "Qǐng lǎngdú: mǎ — dì sān shēng.",
                "bot_english": "Please read: mǎ — Tone 3, dipping.",
                "bot_malay": "Sila baca: mǎ — Nada 3, turun naik.",
                "expected_keywords": ["马", "ma", "tone 3", "第三声"],
                "hint_en": "Say ma (mǎ) with a dipping tone.",
                "hint_ms": "Sebut ma (mǎ) dengan nada turun naik.",
                "speak_target": {
                    "word": "马",
                    "pinyin": "mǎ",
                    "english": "Horse",
                    "malay": "Kuda",
                    "expected_tone": 3,
                    "note": "Tone 3: dip then rise (horse).",
                },
            },
            {
                "id": "tone_ma4",
                "bot": "请朗读：骂 (mà) — Tone 4, falling.",
                "bot_pinyin": "Qǐng lǎngdú: mà — dì sì shēng.",
                "bot_english": "Please read: mà — Tone 4, falling.",
                "bot_malay": "Sila baca: mà — Nada 4, turun.",
                "expected_keywords": ["骂", "ma", "tone 4", "第四声"],
                "hint_en": "Say ma (mà) with a falling tone.",
                "hint_ms": "Sebut ma (mà) dengan nada turun.",
                "speak_target": {
                    "word": "骂",
                    "pinyin": "mà",
                    "english": "To scold",
                    "malay": "Memarahi",
                    "expected_tone": 4,
                    "note": "Tone 4: sharp falling (scold).",
                },
            },
        ],
    },
    "lesson_3_numbers": {
        "title": "Lesson 3 — Numbers",
        "description": "Numbers 1-5 with tone practice.",
        "steps": [
            {
                "id": "num_intro",
                "bot": "我们来学数字 一、二、三、四、五。请回复：开始",
                "bot_pinyin": "Wǒmen lái xué shùzì yī, èr, sān, sì, wǔ.",
                "bot_english": "Let's learn numbers one to five. Reply: start.",
                "bot_malay": "Mari belajar nombor satu hingga lima. Balas: mula.",
                "expected_keywords": ["开始", "好", "start", "kaishi", "mula"],
                "hint_en": "Type start or mula to begin.",
                "hint_ms": "Taip start atau mula untuk mula.",
                "speak_target": None,
            },
            {
                "id": "num_yi",
                "bot": "请说：一 (yī) — Tone 1",
                "bot_pinyin": "Qǐng shuō: yī",
                "bot_english": "Please say: one (yī) — Tone 1.",
                "bot_malay": "Sila sebut: satu (yī) — Nada 1.",
                "expected_keywords": ["一", "yi", "1"],
                "hint_en": "Say yi (yī) — one.",
                "hint_ms": "Sebut yi (yī) — satu.",
                "speak_target": {
                    "word": "一",
                    "pinyin": "yī",
                    "english": "One",
                    "malay": "Satu",
                    "expected_tone": 1,
                    "note": "Tone 1: one.",
                },
            },
            {
                "id": "num_san",
                "bot": "请说：三 (sān) — Tone 1",
                "bot_pinyin": "Qǐng shuō: sān",
                "bot_english": "Please say: three (sān) — Tone 1.",
                "bot_malay": "Sila sebut: tiga (sān) — Nada 1.",
                "expected_keywords": ["三", "san", "3"],
                "hint_en": "Say san (sān) — three.",
                "hint_ms": "Sebut san (sān) — tiga.",
                "speak_target": {
                    "word": "三",
                    "pinyin": "sān",
                    "english": "Three",
                    "malay": "Tiga",
                    "expected_tone": 1,
                    "note": "Tone 1: three.",
                },
            },
        ],
    },
}

TONE_LABELS = {
    1: "Tone 1 — high flat",
    2: "Tone 2 — rising",
    3: "Tone 3 — dipping",
    4: "Tone 4 — falling",
}
